# Generated by Django 2.2 on 2021-07-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='resthouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('room_type', models.CharField(max_length=30, verbose_name='房间类型')),
                ('toward', models.CharField(max_length=15, verbose_name='朝向')),
                ('area', models.FloatField(max_length=10, verbose_name='面积')),
                ('month_price', models.FloatField(max_length=20, verbose_name='月租')),
            ],
        ),
        migrations.CreateModel(
            name='sellhouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('address', models.CharField(max_length=20, verbose_name='地址')),
                ('unit_type', models.CharField(max_length=30, verbose_name='户型')),
                ('created_time', models.CharField(max_length=30, verbose_name='建立时间')),
                ('room_type', models.CharField(max_length=30, verbose_name='房间类型')),
                ('area', models.FloatField(max_length=10, verbose_name='面积')),
                ('toward', models.CharField(max_length=15, verbose_name='朝向')),
                ('total_price', models.FloatField(max_length=10, verbose_name='总价')),
                ('unit_price', models.FloatField(max_length=20, verbose_name='单价')),
                ('follows', models.IntegerField(verbose_name='关注人数')),
            ],
        ),
    ]
